Feature/css
Rocsana/Save-the-World pull request #2
Opened 2020-09-09 09:47 UTC by Rocsana

2020-09-09 09:54 UTC, adinabadila requested changes

2020-09-09 09:54 UTC, adinabadila commented on css/homestyle.css
> +    display: grid;
as vrea sa incerci sa le faci fara grid, sa le faci cu flex si sa te folosesti de multe containere

2020-09-09 09:54 UTC, adinabadila commented on css/homestyle.css
> +.gallery__sheeps {
daca le faci fara grid atunci nu mai trebuie sa ai clasa specifica pentru fiecare poza, gandeste-te daca ar fi 100 de poze, nu ar fi chiar ok sa ai 100 de clase

2020-09-09 09:54 UTC, adinabadila commented on css/homestyle.css
> +
remove line here

2020-09-09 09:54 UTC, adinabadila commented on index.html
> +
remove line here

2020-09-09 14:32 UTC, Rocsana commented on css/homestyle.css
> +    display: grid;
Am reusit sa fac cu flex, daca cumva nu am inteles eu ideea bine, nu e problema ca o rezolv, numai sa stiu.

2020-09-11 09:24 UTC, adinabadila requested changes

2020-09-11 09:24 UTC, adinabadila commented on index.html
> +                <p class="gallery_text">
double __
```suggestion
                <p class="gallery__text">
```

2020-09-11 09:24 UTC, adinabadila commented on index.html
> +                    <div><img  src="./photos/shore.png" alt="Photo of a shore" class="gallery__shore"></div>
hmm, aici de ce le-ai mai pus in div-uri daca nu ai clase pe div?

2020-09-11 09:24 UTC, adinabadila commented on css/homestyle.css
> +.gallery_text {
double _

2020-09-11 09:24 UTC, adinabadila commented on css/homestyle.css
> +
remove line

2020-09-11 09:24 UTC, adinabadila commented on css/homestyle.css
> +
remove line

2020-09-11 09:24 UTC, adinabadila commented on css/homestyle.css
> +
prea multe linii libere

2020-09-11 09:24 UTC, adinabadila commented on css/homestyle.css
> +    .gallery_text {
double _

2020-09-11 09:24 UTC, adinabadila commented on css/homestyle.css
> +    .gallery__shore{
spatiu inainte de {

2020-09-14 17:48 UTC, adinabadila requested changes

2020-09-14 17:48 UTC, adinabadila commented on css/homestyle.css
> +
remove unused line

2020-09-14 17:48 UTC, adinabadila commented on css/homestyle.css
> +
remove unused line

2020-09-14 18:07 UTC, adinabadila approved these changes

2020-09-14 18:07 UTC, merged